### PR TITLE
Patch contacts page and theming according to assignments

### PR DESCRIPTION
**Pull request by TheEgghead27**
Completes the following tasks:
- [x]  Alignment with button on the contact page (85211ddc843ac9a7d5cd9958f3d4f2e3a6df6b23)
- [x]  Contact page circle issue - hidden div on small bps (uncertain) 
- [x]  scroll  text contact us (e945be81ea47e7e58c4c5d745661c1ffcde93bae)
- [x]  Primary color for dark mode is not pure white but E0E0E0 (a34e416a52eb04fb2dff39344e9cdbef837fce3b)

### CODE REVIEW

**Review by leomet07 — APPROVED** [review]
Looks good to me.

**Comment by leomet07** [comment]
On desktop screens, it takes a while for the Contact page's <marquee> to scroll in. Maybe the marquee should only move from the right to left, but stay visible the entire time on desktop?

Or maybe increasing the marquee's speed would help.

Or maybe, this is simply a designed feature.

Just asking.

**Comment by TheEgghead27** [comment]
I defaulted to fully off screen start/end points, but I was hoping for feedback on the speed and/or distance from you and @willpill, feel free to edit it or propose changes as you see fit.

**Comment by leomet07** [comment]
I checked the second check box ( Contact page circle issue - hidden div on small bps ),
as the graphic designer was referring to making the contact page “circle” responsive on/to mobile screens. It’s already perfectly functional and looks good on mobile screens (especially with your latest work :D )

**Comment by TheEgghead27** [comment]
Nice! Then this branch should be ready for merge.

**Review by willpill — APPROVED** [review]
Looks good! Although the scrolling animation has been updated on the Figma. You could include that in a future PR though

**Comment by leomet07** [comment]
I made the marquee bounce around the page, instead of scrolling left infinitely. 
This allows it to be in the center for longer (and at the start), whilst still keeping some animation.

**Pull request merged**
